<?php  //Clase para los jugadores 

class Jugadores
{

    var $name;  //variable donde se guardara el nombre del jugador
    var $score; //variable donde se guardara los puntos del jugador 
    var $Pwin; //varible para guardar cuantas minirondas puso que ganara esta ronda/match
    
    var $Mano; //arreglo donde indica los id de cartas que tiene en mano
    

    function PonerCarta
    {

    }

    /*  Los jugadores tienen una mano
        Pueden poner cartas
        tienen predicciones de ganadas y perdidas
        pueden ser el segundo trump
        tienen puntos
        tienen un nombre 

        deben tener un metodo para poner cartas
        debe tener un metodo para asignar su nombre
        un metodo para ver su score,agregar puntos o quitarlos


    */

}


?>